server:
  port: 8761

spring:
  application:
    name: Eureka-Server # 应用名称
  freemarker:
    prefer-file-system-access: false #该属性表示是否优先从文件系统加载template，以支持热加载，默认值为true，改成false后可成功访问

# 配置 Eureka Server 注册中心  单机版
eureka:
  instance:
    hostname: localhost            # 主机名，不配置的时候将根据操作系统的主机名来获取
  client:
    register-with-eureka: false   # 是否将自己注册到注册中心，默认为 true,单机版本改为false
    fetch-registry: false  # 是否从注册中心获取服务注册信息，默认为 true
    service-url:                  # 注册中心对外暴露的注册地址
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
