server:
  port: 8763

spring:
  application:
    name: Eureka-Server # 应用名称--集群版
  # 安全认证
  security:
    user:
      name: root
      password: 12345tqk
  freemarker:
    prefer-file-system-access: false #该属性表示是否优先从文件系统加载template，以支持热加载，默认值为true，改成false后可成功访问

# 配置 Eureka Server 注册中心  集群版
eureka:
  server:
    enable-self-preservation: false # true：开启自我保护模式，false：关闭自我保护模式
    eviction-interval-timer-in-ms: 10000 # 清理间隔（单位：毫秒，默认是 60*1000）
  instance:
    hostname: Eureka01            # 主机名，不配置的时候将根据操作系统的主机名来获取
    prefer-ip-address: true  # 是否使用 ip 地址注册
    instance-id: ${spring.cloud.client.ip-address}:${server.port} # ip:port
  client:
    # 设置服务注册中心地址，指向另一个注册中心
    service-url:                  # 注册中心对外暴露的注册地址
      defaultZone: http://root:12345tqk@localhost:8762/eureka/
